language: python
before_script:
- wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python37/bin/
- export CHROME_BIN=chromium-browser

script: python test_nopCommerce.py