language: python
before_script:
- wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.6/bin/
- export CHROME_BIN=chromium-browser

script: pytest tests/test_nopCommercecom.py